# Always show gaps
smart_gaps off

gaps inner 5
gaps outer 5

# Automatically move some applications to dedicated workspaces
for_window [app_id="firefox"] move window to workspace $ws3

# Don't allow applications to inhibit shortcuts, i.e. grab total control of the
# keyboard. Chrome currently abuses this by enabling it for all "--app=..."
# shortcuts.
seat * shortcuts_inhibitor disable
