# Window borders
default_border pixel 2

# Always show gaps
smart_gaps off

# Borders will only be enabled if the workspace has more than one visible child.
smart_borders on

gaps inner 5
gaps outer 5
#  vim: set ts=4 sw=4 tw=0 et ft=swayconfig :
