[".oh-my-zsh"]
	type = "archive"
	url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-history-substring-search"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/you-should-use"]
	type = "archive"
	url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/refs/tags/1.7.3.tar.gz"
	exact = true
	stripComponents = 1

[".oh-my-zsh/custom/plugins/chroot"]
	type = "archive"
	url = "https://gist.github.com/hbuyse/854435b018de288c956513561d32504b/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-completions"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-completions/archive/refs/tags/0.33.0.tar.gz"
	exact = true
	stripComponents = 1

[".oh-my-zsh/custom/themes/powerlevel10k"]
	type = "archive"
	url = "https://github.com/romkatv/powerlevel10k/archive/v1.16.1.tar.gz"
	exact = false
	stripComponents = 1

[".local/share/fonts/Hack"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip"
	exact = true

[".local/bin/betterlockscreen"]
	type = "file"
	url = "https://raw.githubusercontent.com/betterlockscreen/betterlockscreen/v4.0.4/betterlockscreen"
	executable = true

[".pyenv"]
	type = "archive"
	url = "https://github.com/pyenv/pyenv/archive/refs/tags/v2.3.5.tar.gz"
	exact = false
	stripComponents = 1

[ ".pyenv/plugins/pyenv-ccache" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-ccache/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-doctor" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-doctor/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-installer" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-installer/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-update" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-update/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-virtualenv" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-virtualenv/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-which-ext" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-which-ext/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".local/bin/nextcloud" ]
	type = "file"
	url = "https://github.com/nextcloud/desktop/releases/download/v3.6.2/Nextcloud-3.6.2-x86_64.AppImage"
	executable = true

[ ".local/bin/bat" ]
    type = "file"
    url = "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/bat".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-v0.22.1-x86_64-unknown-linux-gnu/bat"]
