[".oh-my-zsh"]
	type = "archive"
	url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-history-substring-search"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/you-should-use"]
	type = "archive"
	url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/refs/tags/1.7.3.tar.gz"
	exact = true
	stripComponents = 1

[".oh-my-zsh/custom/plugins/chroot"]
	type = "archive"
	url = "https://gist.github.com/hbuyse/854435b018de288c956513561d32504b/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-completions"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-completions/archive/refs/tags/0.35.0.tar.gz"
	exact = true
	stripComponents = 1

[".oh-my-zsh/custom/themes/powerlevel10k"]
	type = "archive"
	url = "https://github.com/romkatv/powerlevel10k/archive/v1.20.0.tar.gz"
	exact = false
	stripComponents = 1

[".pyenv"]
	type = "archive"
	url = "https://github.com/pyenv/pyenv/archive/refs/tags/v2.3.35.tar.gz"
	exact = false
	stripComponents = 1

[ ".pyenv/plugins/pyenv-ccache" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-ccache/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-doctor" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-doctor/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-installer" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-installer/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-update" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-update/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-virtualenv" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-virtualenv/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-which-ext" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-which-ext/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

{{ if eq .chezmoi.os "linux" -}}
[".local/share/themes/Gruvbox-Dark-Border"]
	type = "archive"
	url = "https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/archive/refs/heads/master.tar.gz"
	exact = false
	refreshPeriod = "168h"
	stripComponents = 3
    include = ["Gruvbox-GTK-Theme-master/themes/Gruvbox-Dark-B/**"]

[".local/share/themes/Gruvbox-Dark-BorderLess"]
	type = "archive"
	url = "https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/archive/refs/heads/master.tar.gz"
	exact = false
	refreshPeriod = "168h"
	stripComponents = 3
    include = ["Gruvbox-GTK-Theme-master/themes/Gruvbox-Dark-BL/**"]

{{ $nerdFontsVersion := "3.1.1" -}}
[".local/share/fonts/Hack"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Hack.tar.xz"
	exact = true

[".local/share/fonts/Iosevka"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Iosevka.tar.xz"
	exact = true

[".local/share/fonts/Meslo"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Meslo.tar.xz"
	exact = true

[".local/share/fonts/Ubuntu"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Ubuntu.tar.xz"
	exact = true

[".local/share/fonts/UbuntuMono"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/UbuntuMono.tar.xz"
	exact = true

[".local/bin/betterlockscreen"]
	type = "file"
	url = "https://raw.githubusercontent.com/betterlockscreen/betterlockscreen/v4.0.4/betterlockscreen"
	executable = true

{{ $nextcloudVersion := "3.11.0" -}}
[ ".local/bin/nextcloud" ]
	type = "file"
	url = "https://github.com/nextcloud-releases/desktop/releases/download/v{{ $nextcloudVersion }}/Nextcloud-{{ $nextcloudVersion }}-x86_64.AppImage"
	executable = true

{{ $batVersion := "0.23.0" -}}
[ ".local/bin/bat" ]
    type = "file"
    url = "https://github.com/sharkdp/bat/releases/download/v{{ $batVersion }}/bat-v{{ $batVersion }}-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/bat".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-v{{ $batVersion }}-x86_64-unknown-linux-gnu/bat"]

[ ".local/bin/nvim" ]
    type = "file"
	url = "https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage"
    executable = true

{{ $luaLsVersion := "3.6.25" -}}
[ ".local/lua-language-server" ]
	type = "archive"
	url = "https://github.com/LuaLS/lua-language-server/releases/download/{{ $luaLsVersion }}/lua-language-server-{{ $luaLsVersion }}-{{ .chezmoi.os }}-x64.tar.gz"
	exact = false

{{ $shfmtVersion := "3.7.0" -}}
[ ".local/bin/shfmt" ]
    type = "file"
	url = "https://github.com/mvdan/sh/releases/download/v{{ $shfmtVersion }}/shfmt_v{{ $shfmtVersion }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}"
    executable = true

{{ $shellcheckVersion := "0.9.0" -}}
[ ".local/bin/shellcheck" ]
    type = "file"
    url = "https://github.com/koalaman/shellcheck/releases/download/v{{ $shellcheckVersion }}/shellcheck-v{{ $shellcheckVersion }}.{{ .chezmoi.os }}.x86_64.tar.xz"
    executable = true
    [".local/bin/shellcheck".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--xz", "--to-stdout", "shellcheck-v{{ $shellcheckVersion }}/shellcheck"]

{{ $bitwardenVersion := "2023.10.0" -}}
[ ".local/bin/bitwarden" ]
    type = "file"
	url = "https://github.com/bitwarden/clients/releases/download/desktop-v{{ $bitwardenVersion }}/Bitwarden-{{ $bitwardenVersion }}-x86_64.AppImage"
    executable = true

{{ $flameshotVersion := "12.1.0" -}}
[ ".local/bin/flameshot" ]
    type = "file"
	url = "https://github.com/flameshot-org/flameshot/releases/download/v{{ $flameshotVersion }}/Flameshot-{{ $flameshotVersion }}.x86_64.AppImage"
    executable = true
{{- end }} {{/* .chezmoi.os "linux" */}}

{{ $fzfVersion := "0.44.1" -}}
[ ".local/bin/fzf" ]
    type = "file"
    url = "https://github.com/junegunn/fzf/releases/download/{{ $fzfVersion }}/fzf-{{ $fzfVersion }}-{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
    executable = true
    [".local/bin/fzf".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "fzf"]

[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"
    refreshPeriod = "168h"
