[".oh-my-zsh"]
	type = "archive"
	url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-history-substring-search"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/you-should-use"]
	type = "archive"
	url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/refs/tags/1.7.3.tar.gz"
	exact = true
	stripComponents = 1

[".oh-my-zsh/custom/plugins/chroot"]
	type = "archive"
	url = "https://gist.github.com/hbuyse/854435b018de288c956513561d32504b/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-completions"]
	type = "archive"
	url = "https://github.com/zsh-users/zsh-completions/archive/refs/tags/0.34.0.tar.gz"
	exact = true
	stripComponents = 1

[".oh-my-zsh/custom/themes/powerlevel10k"]
	type = "archive"
	url = "https://github.com/romkatv/powerlevel10k/archive/v1.18.0.tar.gz"
	exact = false
	stripComponents = 1

[".pyenv"]
	type = "archive"
	url = "https://github.com/pyenv/pyenv/archive/refs/tags/v2.3.23.tar.gz"
	exact = false
	stripComponents = 1

[ ".pyenv/plugins/pyenv-ccache" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-ccache/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-doctor" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-doctor/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-installer" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-installer/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-update" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-update/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-virtualenv" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-virtualenv/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-which-ext" ]
	type = "archive"
	url = "https://github.com/pyenv/pyenv-which-ext/archive/refs/heads/master.tar.gz"
	exact = false
	stripComponents = 1
	refreshPeriod = "168h"

{{ if eq .chezmoi.os "linux" -}}
[".local/share/themes/Gruvbox-Dark-Border"]
	type = "archive"
	url = "https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/archive/refs/heads/master.tar.gz"
	exact = false
	refreshPeriod = "168h"
	stripComponents = 3
    include = ["Gruvbox-GTK-Theme-master/themes/Gruvbox-Dark-B/**"]

[".local/share/themes/Gruvbox-Dark-BorderLess"]
	type = "archive"
	url = "https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/archive/refs/heads/master.tar.gz"
	exact = false
	refreshPeriod = "168h"
	stripComponents = 3
    include = ["Gruvbox-GTK-Theme-master/themes/Gruvbox-Dark-BL/**"]

{{ $nerdFontsVersion := "3.0.2" -}}
[".local/share/fonts/Hack"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Hack.tar.xz"
	exact = true

[".local/share/fonts/Iosevka"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Iosevka.tar.xz"
	exact = true

[".local/share/fonts/Meslo"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Meslo.tar.xz"
	exact = true

[".local/share/fonts/Ubuntu"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Ubuntu.tar.xz"
	exact = true

[".local/share/fonts/UbuntuMono"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/UbuntuMono.tar.xz"
	exact = true

[".local/bin/betterlockscreen"]
	type = "file"
	url = "https://raw.githubusercontent.com/betterlockscreen/betterlockscreen/v4.0.4/betterlockscreen"
	executable = true

{{ $nextcloudVersion := "3.10.0" -}}
[ ".local/bin/nextcloud" ]
	type = "file"
	url = "https://github.com/nextcloud-releases/desktop/releases/download/v{{ $nextcloudVersion }}/Nextcloud-{{ $nextcloudVersion }}-x86_64.AppImage"
	executable = true

{{ $batVersion := "0.23.0" -}}
[ ".local/bin/bat" ]
    type = "file"
    url = "https://github.com/sharkdp/bat/releases/download/v{{ $batVersion }}/bat-v{{ $batVersion }}-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/bat".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-v{{ $batVersion }}-x86_64-unknown-linux-gnu/bat"]

[ ".local/bin/nvim" ]
    type = "file"
	url = "https://github.com/neovim/neovim/releases/download/v0.9.2/nvim.appimage"
    executable = true

{{ $luaLsVersion := "3.6.25" -}}
[ ".local/lua-language-server" ]
	type = "archive"
	url = "https://github.com/LuaLS/lua-language-server/releases/download/{{ $luaLsVersion }}/lua-language-server-{{ $luaLsVersion }}-linux-x64.tar.gz"
	exact = false

{{ $shfmtVersion := "3.7.0" -}}
[ ".local/bin/shfmt" ]
    type = "file"
	url = "https://github.com/mvdan/sh/releases/download/v{{ $shfmtVersion }}/shfmt_v{{ $shfmtVersion }}_linux_amd64"
    executable = true
{{- end }}
