[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-history-substring-search"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/you-should-use"]
    type = "archive"
    url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/refs/tags/1.8.0.tar.gz"
    exact = true
    stripComponents = 1

[".oh-my-zsh/custom/plugins/chroot"]
    type = "archive"
    url = "https://gist.github.com/hbuyse/854435b018de288c956513561d32504b/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/refs/tags/0.35.0.tar.gz"
    exact = true
    stripComponents = 1

[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.20.0.tar.gz"
    exact = false
    stripComponents = 1

[".pyenv"]
    type = "archive"
    url = "https://github.com/pyenv/pyenv/archive/refs/tags/v2.4.8.tar.gz"
    exact = false
    stripComponents = 1

[ ".pyenv/plugins/pyenv-ccache" ]
    type = "archive"
    url = "https://github.com/pyenv/pyenv-ccache/archive/refs/heads/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"

[ ".pyenv/plugins/pyenv-virtualenv" ]
    type = "archive"
    url = "https://github.com/pyenv/pyenv-virtualenv/archive/refs/tags/v1.2.4.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"

{{ if eq .chezmoi.os "linux" -}}
[".local/share/themes/Gruvbox-Dark-Border"]
    type = "archive"
    url = "https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/archive/refs/heads/master.tar.gz"
    exact = false
    refreshPeriod = "168h"
    stripComponents = 3
    include = ["Gruvbox-GTK-Theme-master/themes/Gruvbox-Dark-B/**"]

[".local/share/themes/Gruvbox-Dark-BorderLess"]
    type = "archive"
    url = "https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/archive/refs/heads/master.tar.gz"
    exact = false
    refreshPeriod = "168h"
    stripComponents = 3
    include = ["Gruvbox-GTK-Theme-master/themes/Gruvbox-Dark-BL/**"]

{{ $nerdFontsVersion := "3.2.1" -}}
[".local/share/fonts/Hack"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Hack.tar.xz"
    exact = true

[".local/share/fonts/Iosevka"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Iosevka.tar.xz"
    exact = true

[".local/share/fonts/Meslo"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Meslo.tar.xz"
    exact = true

[".local/share/fonts/Ubuntu"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/Ubuntu.tar.xz"
    exact = true

[".local/share/fonts/UbuntuMono"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontsVersion }}/UbuntuMono.tar.xz"
    exact = true

{{ if eq .session_type "x11" -}}
{{ $betterlockscreenVersion := "bdfc4faf7142aa1d555528ab1a9a103be95a3f80" -}}
[".local/bin/betterlockscreen"]
    type = "file"
    url = "https://raw.githubusercontent.com/betterlockscreen/betterlockscreen/{{ $betterlockscreenVersion }}/betterlockscreen"
    executable = true
{{- end }}{{/* env "XDG_SESSION_TYPE" "x11" */}}

{{ $flameshotVersion := "12.1.0" -}}
[ ".local/bin/flameshot" ]
    type = "file"
    url = "https://github.com/flameshot-org/flameshot/releases/download/v{{ $flameshotVersion }}/Flameshot-{{ $flameshotVersion }}.x86_64.AppImage"
    executable = true
{{- end }} {{/* .chezmoi.os "linux" */}}

{{ if eq .chezmoi.osRelease.id "ubuntu" -}}
{{ $bitwardenVersion := "2024.2.0" -}}
[ ".local/bin/bitwarden" ]
    type = "file"
    url = "https://github.com/bitwarden/clients/releases/download/desktop-v{{ $bitwardenVersion }}/Bitwarden-{{ $bitwardenVersion }}-x86_64.AppImage"
    executable = true

{{ $shfmtVersion := "3.8.0" -}}
[ ".local/bin/shfmt" ]
    type = "file"
    url = "https://github.com/mvdan/sh/releases/download/v{{ $shfmtVersion }}/shfmt_v{{ $shfmtVersion }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}"
    executable = true

{{ $shellcheckVersion := "0.10.0" -}}
[ ".local/bin/shellcheck" ]
    type = "file"
    url = "https://github.com/koalaman/shellcheck/releases/download/v{{ $shellcheckVersion }}/shellcheck-v{{ $shellcheckVersion }}.{{ .chezmoi.os }}.x86_64.tar.xz"
    executable = true
    [".local/bin/shellcheck".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--xz", "--to-stdout", "shellcheck-v{{ $shellcheckVersion }}/shellcheck"]

{{ $luaLsVersion := "3.9.1" -}}
[ ".local/lua-language-server" ]
    type = "archive"
    url = "https://github.com/LuaLS/lua-language-server/releases/download/{{ $luaLsVersion }}/lua-language-server-{{ $luaLsVersion }}-{{ .chezmoi.os }}-x64.tar.gz"
    exact = false

{{ $texlabVersion := "5.15.0" -}}
[ ".local/bin/texlab" ]
    type = "archive-file"
    url = "https://github.com/latex-lsp/texlab/releases/download/v{{ $texlabVersion }}/texlab-x86_64-{{ .chezmoi.os }}.tar.gz"
    executable = true
    path = "texlab"

{{ $nextcloudVersion := "3.14.0" -}}
[ ".local/bin/nextcloud" ]
    type = "file"
    url = "https://github.com/nextcloud-releases/desktop/releases/download/v{{ $nextcloudVersion }}/Nextcloud-{{ $nextcloudVersion }}-x86_64.AppImage"
    executable = true

{{ $direnvVersion := "2.34.0" -}}
[ ".local/bin/direnv" ]
    type = "file"
    url = "https://github.com/direnv/direnv/releases/download/v{{ $direnvVersion }}/direnv.{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
    executable = true

{{ $fzfVersion := "0.54.3" -}}
[ ".local/bin/fzf" ]
    type = "archive-file"
    url = "https://github.com/junegunn/fzf/releases/download/v{{ $fzfVersion }}/fzf-{{ $fzfVersion }}-{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
    executable = true
    path = "fzf"

{{ $fastfetchVersion := "2.21.0" -}}
[ ".local/bin/fastfetch" ]
    type = "archive-file"
    url = "https://github.com/fastfetch-cli/fastfetch/releases/download/{{ $fastfetchVersion }}/fastfetch-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    path = "fastfetch-{{ .chezmoi.os }}-{{ .chezmoi.arch }}/usr/bin/fastfetch"
{{- end }}{{/* .chezmoi.osRelease.id "ubuntu" */}}

{{ $yamlfmtVersion := "0.12.1" -}}
[ ".local/bin/yamlfmt" ]
    type = "archive-file"
    url = "https://github.com/google/yamlfmt/releases/download/v{{ $yamlfmtVersion }}/yamlfmt_{{ $yamlfmtVersion }}_{{ .chezmoi.kernel.ostype }}_x86_64.tar.gz"
    executable = true
    path = "yamlfmt"

[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"
    refreshPeriod = "168h"

{{ if eq .session_type "wayland" -}}
[".local/bin/wlprop"]
    type = "file"
    url = "https://gist.githubusercontent.com/crispyricepc/f313386043395ff06570e02af2d9a8e0/raw/758c548bfb4be5b437c428c8062b3987f126f002/wlprop.sh"
    executable = true
{{- end }}{{/* env "XDG_SESSION_TYPE" "wayland" */}}

{{ $ohMyPoshVersion := "23.10.1" -}}
[".local/bin/oh-my-posh"]
    type = "file"
    url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v{{ $ohMyPoshVersion }}/posh-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
    executable = true
