vim.g.DoxygenToolkit_startCommentTag = '/*!'
vim.g.DoxygenToolkit_startCommentBlock = '/* '
vim.g.DoxygenToolkit_briefTag_pre = '\\brief '
vim.g.DoxygenToolkit_paramTag_pre = '\\param[in, out] '
vim.g.DoxygenToolkit_returnTag = '\\return '
