---
Diagnostics:
    ClangTidy:
        Add:
            - '*'
        Remove:
            - altera-unroll-loops
            - altera-id-dependent-backward-branch
            - llvmlibc-restrict-system-libc-headers
            - readability-braces-around-statements
            - google-readability-braces-around-statements # alias to readability-braces-around-statements
            - hicpp-braces-around-statements # alias to readability-braces-around-statements
            - readability-identifier-length
            - readability-magic-numbers
            - cppcoreguidelines-avoid-magic-numbers
InlayHints:
    Enabled: Yes
    ParameterNames: Yes
    DeducedTypes: Yes
