Diagnostics:
  ClangTidy:
    Add:
      - '*'
    Remove:
      - llvmlibc-restrict-system-libc-headers
      - readability-braces-around-statements
      - google-readability-braces-around-statements  # alias to readability-braces-around-statements
      - hicpp-braces-around-statements               # alias to readability-braces-around-statements
