#! /usr/bin/env bash

cmd_exists () {
    command -v "$1" >/dev/null
}

# Send notification to the user
if cmd_exists notify-send; then
  notify-send -i display "Autorandr" "Using profile '${AUTORANDR_CURRENT_PROFILE}'"
fi

# Reset the background
if cmd_exists feh; then
  feh --bg-fill "${HOME}/.config/wallpapers/wallpaper.png"
fi

# Relaunch the conkies
if cmd_exists conky; then
  "${HOME}/.config/conky/launch.sh"
fi

# Relaunch picom
if cmd_exists picom; then
  "$HOME/.config/picom/launch.sh"
fi

# Start redshift
# if cmd_exists redshift; then
#   $HOME/.config/redshift/launch.sh
# fi

# Update lockscreen
if cmd_exists betterlockscreen; then
  # Kill all betterlockscreen processes
  pkill -9 betterlockscreen
  nohup betterlockscreen -u "$HOME/.config/wallpapers/locker.png" > /dev/null 2>&1 &
fi

# Start polybar
if cmd_exists polybar; then
  sleep 5
  "${HOME}/.config/polybar/launch.sh"
fi

# vim: set ts=2 sw=2 tw=0 et ft=sh :
