#! /usr/bin/env bash

SCRIPT_PATH=$(dirname $(realpath "$0"))

declare -A gifarray

gifarray[bartender_beer]="https://media.giphy.com/media/h8NdYZJGH1ZRe/giphy-downsized.gif"
gifarray[c_est_pas_faux]="https://media1.tenor.com/images/9e2fd8f6f208f6e34a01038859a10b0b/tenor.gif"
gifarray[coffee_coin]="https://media.giphy.com/media/NHUONhmbo448/giphy.gif"
gifarray[come_at_me_penguin]="https://media.giphy.com/media/U7GRtzqJMyVEs/giphy.gif"
gifarray[dancing_oss117]="https://media1.tenor.com/images/4e17dc669ec43adf82da9458ca248efe/tenor.gif"
gifarray[dancing_bambino_oss117]="https://media1.tenor.com/images/85beaf83f7c00910ab22cded382772d7/tenor.gif"
gifarray[dancing_rabbids]="https://media.giphy.com/media/OScDfyJIQaXe/giphy-downsized.gif"
gifarray[dog_patting]="https://media.giphy.com/media/l1LbUHrJb7GpuOHK0/giphy.gif"
gifarray[embarassed_korean]="https://media.giphy.com/media/K1QnLV1caRpuw/giphy-downsized.gif"
gifarray[embarassed_reaction]="https://media.giphy.com/media/3o7btUg31OCi0NXdkY/giphy.gif"
gifarray[explosion_nuclear]="https://media.giphy.com/media/HhTXt43pk1I1W/giphy-downsized.gif"
gifarray[facepalm]="https://media.giphy.com/media/3og0INyCmHlNylks9O/giphy.gif"
gifarray[good_job_computer]="https://media.giphy.com/media/XreQmk7ETCak0/giphy.gif"
gifarray[good_job_rugby]="https://media.giphy.com/media/l378zfJZhyrFQX8EE/giphy-downsized.gif"
gifarray[hallelujah_big_bang_theory]="https://media.giphy.com/media/KAS81mpeo9kkw/giphy.gif"
gifarray[hallelujah_bunny_dance]="https://media.giphy.com/media/MahDrOWLffiMKpiVV0/giphy-downsized.gif"
gifarray[hello_bear]="https://media.giphy.com/media/IThjAlJnD9WNO/source.gif"
gifarray[hello_coffee]="https://media.giphy.com/media/SYM0DZzld3dBOy1gBt/giphy-downsized.gif"
gifarray[hello_jim_carrey]="https://media.giphy.com/media/PK1YQhAoBOpP2/giphy.gif"
gifarray[hello_there_star_wars]="https://media.giphy.com/media/Nx0rz3jtxtEre/giphy-downsized.gif"
gifarray[hello_there_whale]="https://media.giphy.com/media/mW05nwEyXLP0Y/source.gif"
gifarray[hello_tom_hanks]="https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy.gif"
gifarray[kiss_flirt_shaq]="https://media.giphy.com/media/10UUe8ZsLnaqwo/giphy.gif"
gifarray[la_bamboche_c_est_termine]="https://media1.tenor.com/images/3cbe185deac4a7c5787f9bd0e9abe759/tenor.gif"
gifarray[marteau_piqueur]="https://media.giphy.com/media/TLmFNeMSrOw2VxZGvI/giphy-downsized.gif"
gifarray[minions_booty_bum]="https://media1.tenor.com/images/d30c56b02b29cf801d8e7eda27e541d3/tenor.gif"
gifarray[minions_kiss]="https://media1.tenor.com/images/131b59c8710f085956f956524ce632c8/tenor.gif"
gifarray[nan_mais_oh_oss117]="https://media1.tenor.com/images/a4815b3cb29fd15743f1e6ab5008924d/tenor.gif"
gifarray[nuclear_explosion]="https://media.giphy.com/media/HhTXt43pk1I1W/giphy-downsized.gif"
gifarray[oh_shit_cartoon]="https://media.giphy.com/media/vwI4mYEHP8k0w/giphy.gif"
gifarray[oss117_d_accord]="https://media1.tenor.com/images/cd42ce11f3382d97a68a107180b13236/tenor.gif"
gifarray[oss117_mambo]="https://media1.tenor.com/images/4e17dc669ec43adf82da9458ca248efe/tenor.gif"
gifarray[panic_bigbangtheory]="https://media.giphy.com/media/1FMaabePDEfgk/giphy.gif"
gifarray[panic_minions]="https://media.giphy.com/media/lKZEeXJGhU1d6/giphy.gif"
gifarray[panic_spongebob]="https://media.giphy.com/media/HUkOv6BNWc1HO/giphy.gif"
gifarray[pretty_please_alison_brie]="https://media.giphy.com/media/hB8fe00fafdmM/giphy-downsized.gif"
gifarray[pretty_please_puss_in_boots]="https://media.giphy.com/media/qUIm5wu6LAAog/giphy.gif"
gifarray[pretty_please_rabbids]="https://media.giphy.com/media/l3vR99gV3GJzsPcfC/giphy-downsized.gif"
gifarray[rameur]="https://media.giphy.com/media/1figSjF4pYLhS/giphy.gif"
gifarray[rower_head]="https://media.giphy.com/media/hGr6QFua3JuVO/giphy.gif"
gifarray[scared_scream_queens]="https://media.giphy.com/media/Ej0sZ2rPd2uXu/giphy.gif"
gifarray[scared_timon_pumba]="https://media.giphy.com/media/KmTnUKop0AfFm/giphy.gif"
gifarray[seal_beer]="https://media1.tenor.com/images/d393e5444c18f29e9147759d6606fe6e/tenor.gif"
gifarray[seal_with_it]="https://media.giphy.com/media/B86lxbrMSZ0SQ/giphy.gif"
gifarray[ship_it_hyperrpg]="https://media.giphy.com/media/5bvPqNqk9WVCpYPH1q/giphy-downsized.gif"
gifarray[ship_it_sign]="https://media.giphy.com/media/4ZgwMNUYMxHIyFXujF/giphy-downsized.gif"
gifarray[ship_it_thore]="https://media.giphy.com/media/HkA9xsCxJCRWw/giphy.gif"
gifarray[shocked_james_franco]="https://media.giphy.com/media/vA5evXPactVhC/giphy.gif"
gifarray[shocked_meme]="https://media.giphy.com/media/cF7QqO5DYdft6/giphy.gif"
gifarray[shocked_nba]="https://media.giphy.com/media/l3q2SaisWTeZnV9wk/giphy.gif"
gifarray[speechless_castle]="https://media.giphy.com/media/y7kvOYLzas6Ag/giphy-downsized.gif"
gifarray[super_sayan]="https://media.giphy.com/media/mXz3v0UdjrNTO/giphy.gif"
gifarray[thank_you_the_office]="https://media.giphy.com/media/5xtDarmwsuR9sDRObyU/giphy-downsized.gif"
gifarray[t_es_mauvais_oss117]="https://media1.tenor.com/images/a21a28d1e2bb341d7ef7ddd4e8908b37/tenor.gif"
gifarray[this_is_fine]="https://media.giphy.com/media/QMHoU66sBXqqLqYvGO/giphy.gif"
gifarray[weekend_minions]="https://media.giphy.com/media/lqFY9hBTLX7os/giphy.gif"
gifarray[weekend_rabbids]="https://media.giphy.com/media/l2JhBoNin9yhqSDLO/giphy.gif"
gifarray[whats_up_seal]="https://media.giphy.com/media/ypqHf6pQ5kQEg/giphy.gif"
gifarray[yeah]="https://media.giphy.com/media/MSS0COPq80x68/giphy.gif"
gifarray[you_can_do_it]="https://media.giphy.com/media/mmtLWZVKLOqOs/giphy.gif"
gifarray[you_shall_not_pass]="https://media.giphy.com/media/njYrp176NQsHS/source.gif"

for key in "${!gifarray[@]}"
do
	echo -n "Downloading ${key}.gif  ";
	curl --silent --output "${SCRIPT_PATH}/${key}.gif" "${gifarray[$key]}" && echo "OK" || echo "KO"
done
