#! /usr/bin/env bash

cmd_exists() {
    command -v "$1" > /dev/null
}

# Generate background
"${HOME}/.config/wallpapers/generate-bg.sh" "#fbf1c7" "#d65d0e" "#282828"

# Reset the background
if cmd_exists feh; then
    feh --bg-fill "${HOME}/.config/wallpapers/wallpaper"
fi
