#! /usr/bin/env bash

cmd_exists () {
    command -v "$1" >/dev/null
}

# Send notification to the user
if cmd_exists notify-send; then
  notify-send -i display "Autorandr" "Using profile '${AUTORANDR_CURRENT_PROFILE}'"
fi
