#! /usr/bin/env bash

cmd_exists () {
    command -v "$1" >/dev/null
}

# Update lockscreen
if cmd_exists betterlockscreen; then
  # Kill all betterlockscreen processes
  pkill -9 betterlockscreen
  nohup betterlockscreen -u "$HOME/.config/wallpapers/locker.png" > /dev/null 2>&1 &
fi

# vim: set ts=2 sw=2 tw=0 et ft=sh :
