#! /usr/bin/env bash

# Send notification to the user
if command -v notify-send > "/dev/null"; then
  notify-send -i display "Autorandr" "Using profile '${AUTORANDR_CURRENT_PROFILE}'"
fi

# Reset the background
if command -v feh > "/dev/null"; then
  feh --bg-fill ${HOME}/.config/wallpapers/wallpaper.png
fi

# Relaunch the conkies
if command -v feh > "/dev/null"; then
  ${HOME}/.config/conky/launch.sh
fi

# Relaunch picom
if command -v picom > /dev/null; then
  $HOME/.config/picom/launch.sh
fi

# Start polybar
if command -v polybar > /dev/null; then
  $HOME/.config/polybar/launch.sh
fi

# Start redshift
if command -v redshift > /dev/null; then
  $HOME/.config/redshift/launch.sh
fi

# vim: set ts=2 sw=2 tw=0 et ft=sh :
