#! /usr/bin/env bash

# Send notification to the user
if command -v notify-send > "/dev/null"; then
  notify-send -i display "Autorandr" "Using profile '${AUTORANDR_CURRENT_PROFILE}'"
fi

# Reset the background
if command -v feh > "/dev/null"; then
  feh --bg-fill ${HOME}/.config/wallpapers/wallpaper.png
fi

# vim: set ts=2 sw=2 tw=0 et ft=sh :
