#! /usr/bin/env bash
if command -v notify-send > /dev/null; then
	notify-send -i display "Autorandr" "Using profile '${AUTORANDR_CURRENT_PROFILE}'"
fi

# Reset the background
feh --bg-fill ${HOME}/.config/wallpapers/wallpaper.png

# Restart some daemons
for d in "picom" "conky";
do
    ${HOME}/.config/${d}/launch.sh
done
