[cursor]
# Thickness of the cursor relative to the cell width as floating point number from 0.0 to 1.0.
thickness = 0.15

# Cursor blinking interval in milliseconds.
blink_interval = 750

# When this is true, the cursor will be rendered as a hollow box when the window is not focused.
unfocused_hollow = true

# style = { <shape>, <blinking> }
#
# shape = "Block" | "Underline" | "Beam"
# Default: "Block"
# blinking = "Never" | "Off" | "On" | "Always"
#
# Never Prevent the cursor from ever blinking
# Off Disable blinking by default
# On Enable blinking by default
# Always Force the cursor to always blink
# Default: "Off"
style = { shape = "Block", blinking = "On" }

# If the vi mode cursor style is "None" or not specified, it will fall back to the active value of the normal cursor.
vi_mode_style = "None"
