# Font configuration
[font]
# Point size
size = 9.0

# If the bold family is not specified, it will fall back to the value specified for the normal font.
# The `style` can be specified to pick a specific face.
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

# Offset is the extra space around each character. `offset.y` can be thought
# of as modifying the line spacing, and `offset.x` as modifying the letter
# spacing.
offset = { x = 1, y = 1}

# Glyph offset determines the locations of the glyphs within their cells with
# the default being at the bottom. Increasing `x` moves the glyph to the
# right, increasing `y` moves the glyph upward.
glyph_offset = { x = 0, y = 0 }
