#! /usr/bin/env bash

cmd_exists () {
    command -v "$1" >/dev/null
}

# Send notification to the user
if cmd_exists notify-send; then
  notify-send -i display "Autorandr" "Using profile '${AUTORANDR_CURRENT_PROFILE}'"
fi

# Reset the background
if cmd_exists feh; then
  feh --bg-fill ${HOME}/.config/wallpapers/wallpaper.png
fi

# Relaunch the conkies
if cmd_exists conky; then
  ${HOME}/.config/conky/launch.sh
fi

# Relaunch picom
if cmd_exists picom; then
  $HOME/.config/picom/launch.sh
fi

# Start polybar
if cmd_exists polybar; then
  $HOME/.config/polybar/launch.sh
fi

# Start redshift
if cmd_exists redshift; then
  $HOME/.config/redshift/launch.sh
fi

# vim: set ts=2 sw=2 tw=0 et ft=sh :
